### ISSUE TITLE
ASIC diagrams are wobbly?

### ISSUE THREAD

**Issue by mithro** [chipsalliance/fpga-interchange-schema#68]
https://fpga-interchange-schema.readthedocs.io/device_resources.html

![Screenshot from 2021-12-23 10-08-31](https://user-images.githubusercontent.com/21212/147277599-81005319-a2f5-40d8-97f6-f4c4d3ba38e9.png)
![Screenshot from 2021-12-23 10-08-43](https://user-images.githubusercontent.com/21212/147277600-a8953069-91a3-4618-b426-c13d11f63d69.png)

**Comment by mgielda** [comment]
No longer wobbly as far as I can see! Closing.
